security:
    # ======================
    # PASSWORD HASHING
    # ======================
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # ======================
    # USER PROVIDER
    # ======================
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # ======================
    # ROLE HIERARCHY
    # ======================
    role_hierarchy:
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_MANAGER:     ROLE_MAGASINIER

    # ======================
    # FIREWALLS
    # ======================
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            entry_point: App\Security\AppAuthenticator

            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # ======================
    # ACCESS CONTROL
    # ======================
    access_control:
        # 1. Toujours autoriser le login et le logout (PUBLIC)
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }

        # 2. Zones protégées par rôle
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/purchase/request, roles: ROLE_MANAGER }
        - { path: ^/stock, roles: ROLE_MAGASINIER }

        # 3. Tout le reste nécessite d'être connecté (Bloque l'accès anonyme au reste du site)
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10