<<<<<<< HEAD
# config/packages/twig.yaml
twig:
    # Chemin par défaut pour les templates
    default_path: '%kernel.project_dir%/templates'

    # Optionnel : motif des fichiers Twig
    file_name_pattern: '*.twig'

# Configuration spécifique pour l'environnement "test"
=======
twig:
    file_name_pattern: '*.twig'

>>>>>>> 468894121f6e69ae602c641ed085bd24960cddb3
when@test:
    twig:
        strict_variables: true
